number= int(input("Ingrese su numero del 1 al 12: "))
while number<1 or number>12:
    number=int(input("Pongase serio, digite un numero del 1 al 12: "))
print(f"{number} X 1 = {number*1}")
print(f"{number} X 2 = {number*2}")
print(f"{number} X 3 = {number*3}")
print(f"{number} X 4 = {number*4}")
print(f"{number} X 5 = {number*5}")
print(f"{number} X 6 = {number*6}")
print(f"{number} X 7 = {number*7}")
print(f"{number} X 8 = {number*8}")
print(f"{number} X 9 = {number*9}")
print(f"{number} X 10 = {number*10}")
print(f"{number} X 11 = {number*11}")
print(f"{number} X 12 = {number*12}")